import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });
import AuthProvider from '../context/AuthProvider'
import {ReduxProvider} from '../context/storeProvider'
export const metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        
      <body className={inter.className}>
        <ReduxProvider>
        <Navbar/>
        <Toaster position="bottom-center" />
        <main className="flex-1 pt-16"> {/* Adjust the top padding here */}
        {children}
      </main>
        <Footer/>
        </ReduxProvider>
        </body>
        </AuthProvider>
    </html>
  );
}
